site_name: "2022.1_G3_Bazar"

repo_name: "2022.1_G3_Bazar"
repo_url: "https://unbarqdsw2022-1.github.io/2022.1_G3_Bazar/"

theme:
  name: "material"
  language: "pt"
  logo: "assets/favicon.svg"
  favicon: "assets/favicon.svg"
  palette:
    primary: "#fff"
    accent: "#0B4D9B"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Modelagem: site/Modelagem/2.1.1.UMLEstaticos/uml.md
  - Design Sprint: site/Modelagem/2.1.1.UMLEstaticos/uml.md

plugins:
  - search
